{% set name = "oh-my-posh" %}
{% set version = "26.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/JanDeDobbeleer/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 9a9e12cf95cc3419957fe8194a21eaae11d030fe3fb16b8fd2f739d593b0c1f5

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - oh-my-posh --help

about:
  home: https://github.com/JanDeDobbeleer/oh-my-posh
  license: MIT
  license_file:
    - COPYING
    - license-files/
  summary: Prompt theme engine for any shell
  dev_url: https://github.com/JanDeDobbeleer/oh-my-posh

extra:
  recipe-maintainers:
    - danielnachun
