{% set name = "oh-my-posh" %}
{% set version = "26.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/JanDeDobbeleer/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: aefefdd41253310976fac8066a23018e19baef6ee4d8a0de96ae229d18258eb4

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - oh-my-posh --help

about:
  home: https://github.com/JanDeDobbeleer/oh-my-posh
  license: MIT
  license_file:
    - COPYING
    - license-files/
  summary: Prompt theme engine for any shell
  dev_url: https://github.com/JanDeDobbeleer/oh-my-posh

extra:
  recipe-maintainers:
    - danielnachun
