{% set name = "oh-my-posh" %}
{% set version = "25.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/JanDeDobbeleer/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 558e1c2ca09678bed97f7c3f176707a535e5b7380eb16048a2c0d69b4b6e8b6c

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - oh-my-posh --help

about:
  home: https://github.com/JanDeDobbeleer/oh-my-posh
  license: MIT
  license_file:
    - COPYING
    - license-files/
  summary: Prompt theme engine for any shell
  dev_url: https://github.com/JanDeDobbeleer/oh-my-posh

extra:
  recipe-maintainers:
    - danielnachun
