{% set name = "oh-my-posh" %}
{% set version = "26.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/JanDeDobbeleer/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: bc54fc7f2a230db84e4d3855dc1f745099aa311abcc2f31769307d43996ccb7b

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - oh-my-posh --help

about:
  home: https://github.com/JanDeDobbeleer/oh-my-posh
  license: MIT
  license_file:
    - COPYING
    - license-files/
  summary: Prompt theme engine for any shell
  dev_url: https://github.com/JanDeDobbeleer/oh-my-posh

extra:
  recipe-maintainers:
    - danielnachun
