{% set name = "oh-my-posh" %}
{% set version = "25.23.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/JanDeDobbeleer/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: a71e4e88cffd162445bcd971e6bb26676cfe07a2d2d2ef60daeaecdadb6d4bf5

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - oh-my-posh --help

about:
  home: https://github.com/JanDeDobbeleer/oh-my-posh
  license: MIT
  license_file:
    - COPYING
    - license-files/
  summary: Prompt theme engine for any shell
  dev_url: https://github.com/JanDeDobbeleer/oh-my-posh

extra:
  recipe-maintainers:
    - danielnachun
