schema_version: 1

context:
  version: "30.7.0"

package:
  name: oh-my-posh
  version: ${{ version }}

source:
  url: https://github.com/JanDeDobbeleer/oh-my-posh/archive/v${{ version }}.tar.gz
  sha256: 94fb2b8de8c80526e9f76fbc039a652ac9b13b074947c404293f5c9260c478e4

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - oh-my-posh --help

about:
  license: MIT
  license_file:
    - COPYING
    - license-files/
  summary: Prompt theme engine for any shell
  homepage: https://github.com/JanDeDobbeleer/oh-my-posh
  repository: https://github.com/JanDeDobbeleer/oh-my-posh

extra:
  recipe-maintainers:
    - danielnachun
