schema_version: 1

context:
  version: "29.7.1"

package:
  name: oh-my-posh
  version: ${{ version }}

source:
  url: https://github.com/JanDeDobbeleer/oh-my-posh/archive/v${{ version }}.tar.gz
  sha256: bbad9d58bcbda69cef1562b3d433861d31ca31cab67ba555c0805fd73fb73c87

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - oh-my-posh --help

about:
  license: MIT
  license_file:
    - COPYING
    - license-files/
  summary: Prompt theme engine for any shell
  homepage: https://github.com/JanDeDobbeleer/oh-my-posh
  repository: https://github.com/JanDeDobbeleer/oh-my-posh

extra:
  recipe-maintainers:
    - danielnachun
