schema_version: 1

context:
  version: "28.7.0"

package:
  name: oh-my-posh
  version: ${{ version }}

source:
  url: https://github.com/JanDeDobbeleer/oh-my-posh/archive/v${{ version }}.tar.gz
  sha256: 0d7762f70c6abb1c47973ceb7caf53797e1ab0d6f53541261a30c9759e49dd54

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - oh-my-posh --help

about:
  license: MIT
  license_file:
    - COPYING
    - license-files/
  summary: Prompt theme engine for any shell
  homepage: https://github.com/JanDeDobbeleer/oh-my-posh
  repository: https://github.com/JanDeDobbeleer/oh-my-posh

extra:
  recipe-maintainers:
    - danielnachun
