schema_version: 1

context:
  version: "28.8.1"

package:
  name: oh-my-posh
  version: ${{ version }}

source:
  url: https://github.com/JanDeDobbeleer/oh-my-posh/archive/v${{ version }}.tar.gz
  sha256: 8befcff427b56f1a98b2e78204cc41135c1ac0d74281fd663dbcd90c92c7d111

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - oh-my-posh --help

about:
  license: MIT
  license_file:
    - COPYING
    - license-files/
  summary: Prompt theme engine for any shell
  homepage: https://github.com/JanDeDobbeleer/oh-my-posh
  repository: https://github.com/JanDeDobbeleer/oh-my-posh

extra:
  recipe-maintainers:
    - danielnachun
