schema_version: 1

context:
  version: "29.36.0"

package:
  name: oh-my-posh
  version: ${{ version }}

source:
  url: https://github.com/JanDeDobbeleer/oh-my-posh/archive/v${{ version }}.tar.gz
  sha256: 24c26c1819a4ee0a914bc5db1b42c86da569dc1cfa44c2bb5eb247870e47662c

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - oh-my-posh --help

about:
  license: MIT
  license_file:
    - COPYING
    - license-files/
  summary: Prompt theme engine for any shell
  homepage: https://github.com/JanDeDobbeleer/oh-my-posh
  repository: https://github.com/JanDeDobbeleer/oh-my-posh

extra:
  recipe-maintainers:
    - danielnachun
